config/routes.rb
Cats99::Application.routes.draw do
  resources :cats
  resources :cat_rental_requests do
    member do
      put 'approve'
      put 'deny'
    end
  end

  resources :users
  resource :sessions, :only => [:new, :create, :destroy]
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  attr_accessible :age, :birth_date, :color, :name, :sex, :user_id
  validates_inclusion_of :color, in: %w(black white gray calico)
  validates_inclusion_of :sex, in: %w(M F)

  has_many(
    :rental_requests,
    :class_name => 'CatRentalRequest',
    :foreign_key => :cat_id,
    :primary_key => :id,
    dependent: :destroy,
    :order => :start_date
  )

  belongs_to(
    :owner,
    :class_name => "User",
    :foreign_key => :user_id,
    :primary_key => :id
  )

end

app/models/cat_rental_request.rb
require 'debugger'

class CatRentalRequest < ActiveRecord::Base
  attr_accessible :cat_id, :start_date, :end_date, :status
  before_save :default_values
  validates_inclusion_of :status, in: %w(PENDING APPROVED DENIED)
  validate :overlapping_approved_requests

  def default_values
    self.status ||= 'PENDING'
  end

  belongs_to(
    :cat,
    :class_name => 'Cat',
    :foreign_key => :cat_id,
    :primary_key => :id
  )

  def approve!
    self.status = "APPROVED"
    ActiveRecord::Base.transaction do
      self.status = "APPROVED"
      self.save!
      overlapping_pending_requests.each do |request|
        request.status = "DENIED"
        request.save!
      end
    end
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end

  def range_overlap?(request1, request2)
    x, y = request1, request2
    (x.start_date - y.end_date) * (y.start_date - x.end_date) >= 0
  end

  def overlapping_requests
    cat = Cat.find(self.cat_id)

    overlapping_requests = []
    cat.rental_requests.each do |request|
      overlapping_requests << request if range_overlap?(self, request)
    end

    overlapping_requests
  end

  def overlapping_approved_requests
    overlapping_approved = []
    #debugger
    overlapping_requests.each do |request|
      overlapping_approved << request if request.status == "APPROVED"
    end

    if self.status != "DENIED" && overlapping_approved.any?
      errors.add(:start_date, "Date range conflict")
    end

  end

  def overlapping_pending_requests
    overlapping_pending = []
    overlapping_requests.each do |request|
      overlapping_pending << request if request.status == "PENDING"
    end

    overlapping_pending
  end



end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :user_name, :password_digest, :session_token, :password
  attr_reader :password
  validates :user_name, :presence => true, :uniqueness => true
  validates :password_digest, :presence => true
  validates :password, length: { minimum: 6 }, allow_nil: true
  validates :session_token, presence: true
  before_validation :ensure_session_token

  has_many(
    :cats,
    :class_name => "Cat",
    :foreign_key => :user_id,
    :primary_key => :id
  )


  def self.find_by_credentials(user_name, password)
    user = User.find_by_user_name(user_name)
    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  before_filter :ensure_ownerness, only: [:approve, :deny]

  def new
    @cats = Cat.all
    render :new
  end

  def create
    CatRentalRequest.create!(params[:cat_rental_request])

    redirect_to cat_rental_requests_url
  end

  def index
    @cat_rental_requests = CatRentalRequest.all
  end

  def approve
    @cat_rental_request = CatRentalRequest.find(params[:id])
    @cat_rental_request.approve!
    flash[:notices] = "Your request was approved"
    redirect_to cats_url
  end

  def deny
    @cat_rental_request = CatRentalRequest.find(params[:id])
    @cat_rental_request.deny!
    flash[:notices] = "Your request was denied"
    redirect_to cats_url
  end

  private
  def ensure_ownerness
    @cat_rental_request = CatRentalRequest.find(params[:id])
    unless @cat_rental_request.cat.owner.id == current_user.id
      redirect_to cats_url
    end
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  before_filter :ensure_ownerness, only: [:edit, :update]

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find_by_id(params[:id])
    @rental_requests = @cat.rental_requests
  end

  def new
    @cat = Cat.new

    render :new
  end

  def create
    # Add validation
    c = Cat.create!(params[:cat])
    c.user_id = self.current_user.id
    c.save!

    redirect_to cat_url(c)
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    c = Cat.find(params[:id])
    c.update_attributes(params[:cat])

    redirect_to cat_url(c)
  end

  private
  def ensure_ownerness
    @cat = Cat.find_by_id(params[:id])
    unless @cat.user_id == current_user.id
      redirect_to cats_url
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # def new
  # end

  def create
    @user = User.find_by_credentials(
      params[:user][:user_name],
      params[:user][:password]
    )

    if @user.nil?
      flash.now[:notices] = "Invalid login"
    else
      session[:session_token] = @user.session_token
      @current_user = @user
    end
    redirect_to user_url(@user)
  end

  def destroy
    @user = User.find_by_session_token(session[:session_token])
    @user.reset_session_token!
    session[:session_token] = nil
    redirect_to cats_url
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])



    if @user.save
      flash[:notice] = "User Saved"
      self.current_user = @user
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end


  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)

    @current_user = user
    session[:session_token] = user.session_token

  end


  def login_user!
    # @user = User.find_by_credentials(
#       params[:user][:user_name],
#       params[:user][:password]
#     )
#
#     if @user.nil?
#       flash.now[:notices] = "Invalid login"
#     else
#       new_token = @user.reset_session_token!
#       session[:session_token] = new_token
#       @current_user = @user
#     end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/index.html.erb
<%= @cat_rental_requests.each do |request| %>
  <%= request.cat_id %>
<% end %>

app/views/cat_rental_requests/new.html.erb
<form action="/cat_rental_requests" method="POST">

  <label for="cat_request">Cat Request</label>

  <select name="cat_rental_request[cat_id]">

    <% @cats.each do |cat| %>
      <option value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>

  </select>

  <label for="cat_start_date">Start Date</label>
  <!-- click on the date will launch a date picker -->
  <input name="cat_rental_request[start_date]" id="cat_start_date" type="date"></input>

  <label for="cat_end_date">End Date</label>
  <!-- click on the date will launch a date picker -->
  <input name="cat_rental_request[end_date]" id="cat_end_date" type="date"></input>

  <input type="submit" value="Request Cat!">

</form>

app/views/cats/_form.html.erb
<!-- To do this, we need to get three things right:
The edit form tries to use a Cat's values to pre-fill the fields. The new form doesn't have an existing cat, though.
The edit form posts to cat_url(cat); we want to post to cats_url if we're making a new cat.
The edit form makes a PUT request; we want to make a POST reqeust.
To solve this, build (but don't save) a blank Cat object in the #new action. Set this to @cat.
All the pre-filling should get the blank values.
Use #persisted? to conditionally use cat_url(cat)/PUT only if the Cat has been previously saved to the DB. -->


<form action="<%= url %>" method="POST">


  <!-- label's `for` attribute connects with the input's `id` attribute-->
  <label for="name">name</label>
  <!-- input name `cat[name]` means that Rails will nest the `name` attribute
       inside a `cat` hash: `{ :cat => { :name => "gizmo" } }` -->
  <input name="cat[name]" id="name" type="text" value="<%= @cat.name %>">
  <br>

  <label for="cat_age">Age</label>
  <input name="cat[age]" id="cat_age" type="number" value="<%= @cat.age %>">
  <br>

  <!-- this label isn't for anything specific -->
  <label>Sex</label>
  <div>
    <!-- note that both radio buttons have the name `cat[sex]`; that's how
         they are related -->
    <input name="cat[sex]" id="cat_sex_m" type="radio" value="M" checked="<%= @cat.sex == "M" ? "True" : "False" %>">
    <label for="cat_sex_m">Male</label>
    <input name="cat[sex]" id="cat_sex_f" type="radio" value="F" checked="<%= @cat.sex == "M" ? "True" : "False" %>">
    <label for="cat_sex_f">Female</label>
  </div>
  <br>


  <label for="cat_color">color</label>
  <!-- dropdown -->
  <select name="cat[color]">
    <!-- `brown` is the value that will be submitted to the server; user is
         displayed "Brown" as the choice -->
    <option value=""></option>
    <option value="white"  <%= "selected" if @cat.color == "white"         %>>White</option>
    <option value="black" <%= "selected" if @cat.color == "black"         %>>Black</option>
    <option value="gray" <%= "selected" if @cat.color == "gray"%>
    >Gray</option>
    <option value="calico" <%= "selected" if @cat.color == "calico"         %>>Calico</option>
  </select>
  <br>

  <!-- CHECK MDN FOR DATE PROMPT -->
  <label for="cat_birth_date">Birth date</label>
  <!-- click on the date will launch a date picker -->
  <input name="cat[birth_date]" id="cat_birth_date" type="date"
      value="2000-12-12"
  ></input>

  <!-- <input type="hidden" name="_method" value="PUT"> -->
  <input type="hidden" name="_method" value="<%= hidden_value%>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Build my cat!">



  <!--
    Other uncovered input types:
    hidden field
    check box
    -->
</form>

app/views/cats/edit.html.erb
<h2>Edit cat form!</h2>
<%= render "form", :cat => @cat, :hidden_value => "PUT", :url => cat_url(@cat) %>

app/views/cats/index.html.erb
<% @cats.each do |cat| %>
  <%= cat.name %>
  <%= link_to "#{cat.name}", cat_url(cat) %>
<% end %>

app/views/cats/new.html.erb
<h2>Cat form!</h2>
<%= render "form", :cat => @cat, :action => :new, :hidden_value => "POST", :url => cats_url %>

app/views/cats/show.html.erb
<table>
  <th>Cat</th>
  <tr>
    <td>Name</td>
    <td>Age</td>
    <td>Birth Date</td>
    <td>Sex</td>
    <td>Color</td>
  </tr>

  <tr>
    <td><%= @cat.name %></td>
    <td><%= @cat.age %></td>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.color %></td>
  </tr>
</table>

<br>
<br>

<table>
  <th>Rental Requests</th>
  <tr>
    <td>Start Date</td>
    <td>End Date</td>
  </tr>

  <% @rental_requests.each do |request| %>
  <tr>
    <td><%= request.start_date %></td>
    <td><%= request.end_date %></td>

    <% if request.status == "PENDING" && @cat.user_id == self.current_user.id %>
      <td><%= button_to "Approve Request", approve_cat_rental_request_url(request), method: :put %></td>
      <td><%= button_to "Deny Request", deny_cat_rental_request_url(request), method: :put  %></td>
    <% end %>


  </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if Rails.env.development? %>
  <%= debug params %>
  <br>
  <%= debug session %>
  <br>
  <hr>
  <% end %>
  <% if flash[:notice] %>
      <%= flash[:notice] %>
  <% end %>

  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <%= error %>
    <% end%>
  <% end %>

  <% if current_user %>
    You are logged in as <%= current_user.user_name %>
    <%= button_to "Log Out", sessions_url, method: :delete %>
  <% else %>
    <%= link_to "Sign In", new_sessions_url, method: :get %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<form action="<%= users_url %>" method="POST">
  <label for="user_name">User Name</label>
  <input type="text" name="user[user_name]" id="user_name">

  <label for="password">Password</label>
  <input type="password" name="user[password]" id="password">



  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" value="Create User">
</form>

app/views/users/show.html.erb
<%= @user.user_name %>